version: "3.8"

networks:
  app_tier:
    driver: bridge

volumes:
  postgres_volume:
    driver: local

services:
  ui:
    image: bloated/ui
    build: ./ui
    networks:
      - app_tier
    ports:
      - ${BLOATED_UI_PORT}:3000
    restart: unless-stopped
    environment:
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - ADDRESS_HEADER=x-forwarded-for
      - XFF_DEPTH=1
      - BANNED_IP_FILE=${BLOATED_UI_BANNED_IP_FILE}

  api:
    image: bloated/api
    build: ./api
    networks:
      - app_tier
    restart: unless-stopped
    environment:
      - APP_HTTP_PORT=8080
      - APP_POSTGRES_HOST=postgres
      - APP_POSTGRES_PORT=5432

  postgres:
    image: bitnami/postgresql:15-debian-11
    networks:
      - app_tier
    ports:
      - ${BLOATED_PG_PORT}:5432
    restart: unless-stopped
    volumes:
      - postgres_volume:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=${BLOATED_PG_PASSWORD} # password for `postgres` superuser
