kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "bloated-api.fullname" . }}
  labels:
    {{- include "bloated-api.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
