apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bloated-api.fullname" . }}-rsa
type: Opaque
data:
  jwtRS256.key: {{ .Values.cert.privateKey | b64enc }}
  jwtRS256.key.pub: {{ .Values.cert.publicKey | b64enc }}
