-- Create "token_histories" table
CREATE TABLE "token_histories" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "email" character varying NOT NULL, "user_name" character varying NOT NULL, PRIMARY KEY ("id"));
