-- Create "banned_ips" table
CREATE TABLE "banned_ips" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "ip" character varying NOT NULL, "country" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "todos" table
CREATE TABLE "todos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "user_id" character varying NOT NULL, "task" character varying NOT NULL, PRIMARY KEY ("id"));
