// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isutare412/bloated/api/pkg/core/ent/bannedip"
)

// BannedIPCreate is the builder for creating a BannedIP entity.
type BannedIPCreate struct {
	config
	mutation *BannedIPMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (bic *BannedIPCreate) SetCreateTime(t time.Time) *BannedIPCreate {
	bic.mutation.SetCreateTime(t)
	return bic
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (bic *BannedIPCreate) SetNillableCreateTime(t *time.Time) *BannedIPCreate {
	if t != nil {
		bic.SetCreateTime(*t)
	}
	return bic
}

// SetUpdateTime sets the "update_time" field.
func (bic *BannedIPCreate) SetUpdateTime(t time.Time) *BannedIPCreate {
	bic.mutation.SetUpdateTime(t)
	return bic
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (bic *BannedIPCreate) SetNillableUpdateTime(t *time.Time) *BannedIPCreate {
	if t != nil {
		bic.SetUpdateTime(*t)
	}
	return bic
}

// SetIP sets the "ip" field.
func (bic *BannedIPCreate) SetIP(s string) *BannedIPCreate {
	bic.mutation.SetIP(s)
	return bic
}

// SetCountry sets the "country" field.
func (bic *BannedIPCreate) SetCountry(s string) *BannedIPCreate {
	bic.mutation.SetCountry(s)
	return bic
}

// Mutation returns the BannedIPMutation object of the builder.
func (bic *BannedIPCreate) Mutation() *BannedIPMutation {
	return bic.mutation
}

// Save creates the BannedIP in the database.
func (bic *BannedIPCreate) Save(ctx context.Context) (*BannedIP, error) {
	bic.defaults()
	return withHooks(ctx, bic.sqlSave, bic.mutation, bic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bic *BannedIPCreate) SaveX(ctx context.Context) *BannedIP {
	v, err := bic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bic *BannedIPCreate) Exec(ctx context.Context) error {
	_, err := bic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bic *BannedIPCreate) ExecX(ctx context.Context) {
	if err := bic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bic *BannedIPCreate) defaults() {
	if _, ok := bic.mutation.CreateTime(); !ok {
		v := bannedip.DefaultCreateTime()
		bic.mutation.SetCreateTime(v)
	}
	if _, ok := bic.mutation.UpdateTime(); !ok {
		v := bannedip.DefaultUpdateTime()
		bic.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bic *BannedIPCreate) check() error {
	if _, ok := bic.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "BannedIP.create_time"`)}
	}
	if _, ok := bic.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "BannedIP.update_time"`)}
	}
	if _, ok := bic.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "BannedIP.ip"`)}
	}
	if v, ok := bic.mutation.IP(); ok {
		if err := bannedip.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "BannedIP.ip": %w`, err)}
		}
	}
	if _, ok := bic.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "BannedIP.country"`)}
	}
	if v, ok := bic.mutation.Country(); ok {
		if err := bannedip.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "BannedIP.country": %w`, err)}
		}
	}
	return nil
}

func (bic *BannedIPCreate) sqlSave(ctx context.Context) (*BannedIP, error) {
	if err := bic.check(); err != nil {
		return nil, err
	}
	_node, _spec := bic.createSpec()
	if err := sqlgraph.CreateNode(ctx, bic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bic.mutation.id = &_node.ID
	bic.mutation.done = true
	return _node, nil
}

func (bic *BannedIPCreate) createSpec() (*BannedIP, *sqlgraph.CreateSpec) {
	var (
		_node = &BannedIP{config: bic.config}
		_spec = sqlgraph.NewCreateSpec(bannedip.Table, sqlgraph.NewFieldSpec(bannedip.FieldID, field.TypeInt))
	)
	if value, ok := bic.mutation.CreateTime(); ok {
		_spec.SetField(bannedip.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := bic.mutation.UpdateTime(); ok {
		_spec.SetField(bannedip.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := bic.mutation.IP(); ok {
		_spec.SetField(bannedip.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := bic.mutation.Country(); ok {
		_spec.SetField(bannedip.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	return _node, _spec
}

// BannedIPCreateBulk is the builder for creating many BannedIP entities in bulk.
type BannedIPCreateBulk struct {
	config
	builders []*BannedIPCreate
}

// Save creates the BannedIP entities in the database.
func (bicb *BannedIPCreateBulk) Save(ctx context.Context) ([]*BannedIP, error) {
	specs := make([]*sqlgraph.CreateSpec, len(bicb.builders))
	nodes := make([]*BannedIP, len(bicb.builders))
	mutators := make([]Mutator, len(bicb.builders))
	for i := range bicb.builders {
		func(i int, root context.Context) {
			builder := bicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BannedIPMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bicb *BannedIPCreateBulk) SaveX(ctx context.Context) []*BannedIP {
	v, err := bicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bicb *BannedIPCreateBulk) Exec(ctx context.Context) error {
	_, err := bicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bicb *BannedIPCreateBulk) ExecX(ctx context.Context) {
	if err := bicb.Exec(ctx); err != nil {
		panic(err)
	}
}
