// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isutare412/bloated/api/pkg/core/ent/bannedip"
	"github.com/isutare412/bloated/api/pkg/core/ent/predicate"
)

// BannedIPDelete is the builder for deleting a BannedIP entity.
type BannedIPDelete struct {
	config
	hooks    []Hook
	mutation *BannedIPMutation
}

// Where appends a list predicates to the BannedIPDelete builder.
func (bid *BannedIPDelete) Where(ps ...predicate.BannedIP) *BannedIPDelete {
	bid.mutation.Where(ps...)
	return bid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bid *BannedIPDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bid.sqlExec, bid.mutation, bid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bid *BannedIPDelete) ExecX(ctx context.Context) int {
	n, err := bid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bid *BannedIPDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bannedip.Table, sqlgraph.NewFieldSpec(bannedip.FieldID, field.TypeInt))
	if ps := bid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bid.mutation.done = true
	return affected, err
}

// BannedIPDeleteOne is the builder for deleting a single BannedIP entity.
type BannedIPDeleteOne struct {
	bid *BannedIPDelete
}

// Where appends a list predicates to the BannedIPDelete builder.
func (bido *BannedIPDeleteOne) Where(ps ...predicate.BannedIP) *BannedIPDeleteOne {
	bido.bid.mutation.Where(ps...)
	return bido
}

// Exec executes the deletion query.
func (bido *BannedIPDeleteOne) Exec(ctx context.Context) error {
	n, err := bido.bid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bannedip.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bido *BannedIPDeleteOne) ExecX(ctx context.Context) {
	if err := bido.Exec(ctx); err != nil {
		panic(err)
	}
}
