// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isutare412/bloated/api/pkg/core/ent/predicate"
	"github.com/isutare412/bloated/api/pkg/core/ent/tokenhistory"
)

// TokenHistoryQuery is the builder for querying TokenHistory entities.
type TokenHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []tokenhistory.OrderOption
	inters     []Interceptor
	predicates []predicate.TokenHistory
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TokenHistoryQuery builder.
func (thq *TokenHistoryQuery) Where(ps ...predicate.TokenHistory) *TokenHistoryQuery {
	thq.predicates = append(thq.predicates, ps...)
	return thq
}

// Limit the number of records to be returned by this query.
func (thq *TokenHistoryQuery) Limit(limit int) *TokenHistoryQuery {
	thq.ctx.Limit = &limit
	return thq
}

// Offset to start from.
func (thq *TokenHistoryQuery) Offset(offset int) *TokenHistoryQuery {
	thq.ctx.Offset = &offset
	return thq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (thq *TokenHistoryQuery) Unique(unique bool) *TokenHistoryQuery {
	thq.ctx.Unique = &unique
	return thq
}

// Order specifies how the records should be ordered.
func (thq *TokenHistoryQuery) Order(o ...tokenhistory.OrderOption) *TokenHistoryQuery {
	thq.order = append(thq.order, o...)
	return thq
}

// First returns the first TokenHistory entity from the query.
// Returns a *NotFoundError when no TokenHistory was found.
func (thq *TokenHistoryQuery) First(ctx context.Context) (*TokenHistory, error) {
	nodes, err := thq.Limit(1).All(setContextOp(ctx, thq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tokenhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (thq *TokenHistoryQuery) FirstX(ctx context.Context) *TokenHistory {
	node, err := thq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TokenHistory ID from the query.
// Returns a *NotFoundError when no TokenHistory ID was found.
func (thq *TokenHistoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = thq.Limit(1).IDs(setContextOp(ctx, thq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tokenhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (thq *TokenHistoryQuery) FirstIDX(ctx context.Context) int {
	id, err := thq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TokenHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TokenHistory entity is found.
// Returns a *NotFoundError when no TokenHistory entities are found.
func (thq *TokenHistoryQuery) Only(ctx context.Context) (*TokenHistory, error) {
	nodes, err := thq.Limit(2).All(setContextOp(ctx, thq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tokenhistory.Label}
	default:
		return nil, &NotSingularError{tokenhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (thq *TokenHistoryQuery) OnlyX(ctx context.Context) *TokenHistory {
	node, err := thq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TokenHistory ID in the query.
// Returns a *NotSingularError when more than one TokenHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (thq *TokenHistoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = thq.Limit(2).IDs(setContextOp(ctx, thq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tokenhistory.Label}
	default:
		err = &NotSingularError{tokenhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (thq *TokenHistoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := thq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TokenHistories.
func (thq *TokenHistoryQuery) All(ctx context.Context) ([]*TokenHistory, error) {
	ctx = setContextOp(ctx, thq.ctx, "All")
	if err := thq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TokenHistory, *TokenHistoryQuery]()
	return withInterceptors[[]*TokenHistory](ctx, thq, qr, thq.inters)
}

// AllX is like All, but panics if an error occurs.
func (thq *TokenHistoryQuery) AllX(ctx context.Context) []*TokenHistory {
	nodes, err := thq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TokenHistory IDs.
func (thq *TokenHistoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if thq.ctx.Unique == nil && thq.path != nil {
		thq.Unique(true)
	}
	ctx = setContextOp(ctx, thq.ctx, "IDs")
	if err = thq.Select(tokenhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (thq *TokenHistoryQuery) IDsX(ctx context.Context) []int {
	ids, err := thq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (thq *TokenHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, thq.ctx, "Count")
	if err := thq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, thq, querierCount[*TokenHistoryQuery](), thq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (thq *TokenHistoryQuery) CountX(ctx context.Context) int {
	count, err := thq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (thq *TokenHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, thq.ctx, "Exist")
	switch _, err := thq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (thq *TokenHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := thq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TokenHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (thq *TokenHistoryQuery) Clone() *TokenHistoryQuery {
	if thq == nil {
		return nil
	}
	return &TokenHistoryQuery{
		config:     thq.config,
		ctx:        thq.ctx.Clone(),
		order:      append([]tokenhistory.OrderOption{}, thq.order...),
		inters:     append([]Interceptor{}, thq.inters...),
		predicates: append([]predicate.TokenHistory{}, thq.predicates...),
		// clone intermediate query.
		sql:  thq.sql.Clone(),
		path: thq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TokenHistory.Query().
//		GroupBy(tokenhistory.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (thq *TokenHistoryQuery) GroupBy(field string, fields ...string) *TokenHistoryGroupBy {
	thq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TokenHistoryGroupBy{build: thq}
	grbuild.flds = &thq.ctx.Fields
	grbuild.label = tokenhistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TokenHistory.Query().
//		Select(tokenhistory.FieldCreateTime).
//		Scan(ctx, &v)
func (thq *TokenHistoryQuery) Select(fields ...string) *TokenHistorySelect {
	thq.ctx.Fields = append(thq.ctx.Fields, fields...)
	sbuild := &TokenHistorySelect{TokenHistoryQuery: thq}
	sbuild.label = tokenhistory.Label
	sbuild.flds, sbuild.scan = &thq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TokenHistorySelect configured with the given aggregations.
func (thq *TokenHistoryQuery) Aggregate(fns ...AggregateFunc) *TokenHistorySelect {
	return thq.Select().Aggregate(fns...)
}

func (thq *TokenHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range thq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, thq); err != nil {
				return err
			}
		}
	}
	for _, f := range thq.ctx.Fields {
		if !tokenhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if thq.path != nil {
		prev, err := thq.path(ctx)
		if err != nil {
			return err
		}
		thq.sql = prev
	}
	return nil
}

func (thq *TokenHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TokenHistory, error) {
	var (
		nodes = []*TokenHistory{}
		_spec = thq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TokenHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TokenHistory{config: thq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, thq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (thq *TokenHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := thq.querySpec()
	_spec.Node.Columns = thq.ctx.Fields
	if len(thq.ctx.Fields) > 0 {
		_spec.Unique = thq.ctx.Unique != nil && *thq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, thq.driver, _spec)
}

func (thq *TokenHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tokenhistory.Table, tokenhistory.Columns, sqlgraph.NewFieldSpec(tokenhistory.FieldID, field.TypeInt))
	_spec.From = thq.sql
	if unique := thq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if thq.path != nil {
		_spec.Unique = true
	}
	if fields := thq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokenhistory.FieldID)
		for i := range fields {
			if fields[i] != tokenhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := thq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := thq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := thq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := thq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (thq *TokenHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(thq.driver.Dialect())
	t1 := builder.Table(tokenhistory.Table)
	columns := thq.ctx.Fields
	if len(columns) == 0 {
		columns = tokenhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if thq.sql != nil {
		selector = thq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if thq.ctx.Unique != nil && *thq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range thq.predicates {
		p(selector)
	}
	for _, p := range thq.order {
		p(selector)
	}
	if offset := thq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := thq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TokenHistoryGroupBy is the group-by builder for TokenHistory entities.
type TokenHistoryGroupBy struct {
	selector
	build *TokenHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (thgb *TokenHistoryGroupBy) Aggregate(fns ...AggregateFunc) *TokenHistoryGroupBy {
	thgb.fns = append(thgb.fns, fns...)
	return thgb
}

// Scan applies the selector query and scans the result into the given value.
func (thgb *TokenHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, thgb.build.ctx, "GroupBy")
	if err := thgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenHistoryQuery, *TokenHistoryGroupBy](ctx, thgb.build, thgb, thgb.build.inters, v)
}

func (thgb *TokenHistoryGroupBy) sqlScan(ctx context.Context, root *TokenHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(thgb.fns))
	for _, fn := range thgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*thgb.flds)+len(thgb.fns))
		for _, f := range *thgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*thgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := thgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TokenHistorySelect is the builder for selecting fields of TokenHistory entities.
type TokenHistorySelect struct {
	*TokenHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ths *TokenHistorySelect) Aggregate(fns ...AggregateFunc) *TokenHistorySelect {
	ths.fns = append(ths.fns, fns...)
	return ths
}

// Scan applies the selector query and scans the result into the given value.
func (ths *TokenHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ths.ctx, "Select")
	if err := ths.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenHistoryQuery, *TokenHistorySelect](ctx, ths.TokenHistoryQuery, ths, ths.inters, v)
}

func (ths *TokenHistorySelect) sqlScan(ctx context.Context, root *TokenHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ths.fns))
	for _, fn := range ths.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ths.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ths.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
