// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BannedIP is the predicate function for bannedip builders.
type BannedIP func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
