app: bloated-api
environment: local
version: development
log:
  development: true
  format: text # text / json
  level: debug # debug / info / warn / error / panic / fatal
  stackTrace: false
  caller: false
http:
  host: "0.0.0.0"
  port: 18080
postgres:
  host: localhost
  port: 28032
  database: bloated_api
  user: api_admin
  password: admin312
jwt:
  tokenTTL: 720h
  privateKey: keys/jwtRS256.key
  publicKey: keys/jwtRS256.key.pub
service:
  maxTodoCountPerUser: 100
