###
POST {{apiUrl}}/api/v1/tokens
Content-Type: application/json

{
    "name": "이수혁",
    "givenName": "수혁",
    "familyName": "이",
    "email": "foo@gmail.com"
}

###
POST {{apiUrl}}/api/v1/tokens?issuer=google
Content-Type: application/json

{
    "token": "<idToken>"
}

###
POST {{apiUrl}}/api/v1/todos
Content-Type: application/json

{
    "userId": "redshore",
    "task": "one"
}

###
GET {{apiUrl}}/api/v1/todos?userid=redshore

###
DELETE  {{apiUrl}}/api/v1/todos/1

###
GET {{apiUrl}}/api/v1/banned-ips
